In [2]:
#pip install numpy

In [3]:
import numpy as n

In [6]:
a=n.array(80)
print(a)
print(type(a))
print(a.ndim)

80
<class 'numpy.ndarray'>
0


In [7]:
b=n.array([1,2,3,4])
print(b)
print(type(b))
print(b.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [8]:
c=n.array([[1,2,3,4],[5,6,7,8]])
print(c)
print(type(c))
print(c.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2


In [10]:
d=n.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(d)
print(type(d))
print(d.ndim)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
<class 'numpy.ndarray'>
3


In [11]:
a=[1,2,3,4]
b=[1,2,3,4]
print(a+b)

[1, 2, 3, 4, 1, 2, 3, 4]


In [12]:
a=n.array([1,2,3,4])
b=n.array([1,2,3,4])
print(a+b)

[2 4 6 8]


In [13]:
a=n.array([1,2,3,4])
b=n.array([1,2,3,4])
print(a*b)

[ 1  4  9 16]


In [14]:
print(n.sum(a))

10


In [15]:
print(n.mean(b))

2.5
